### ISSUE TITLE
Free or alternative option for API

### ISSUE THREAD

**Issue by bpurinton** [appdev-projects/sinatra-exchange-rates#5]
We now need to supply a paid API token for https://exchangerate.host/dashboard

Would this work as a free alternative? https://app.freecurrencyapi.com/dashboard

We will wait to see if offering our paid API token is still creating issues of students publishing the token and it then getting flagged and blocked. If that keeps happening we will need a work around.

**Comment by bpurinton** [comment]
Moving this to the lesson repo rather than the project repo

**Comment by raghubetina** [comment]
One thing I liked about making them get their own API key in an instance where obtaining the key is really easy (e.g. Dark Sky was great for this) is that it makes it "real" for them that the API tokens we later provide are also something that they can obtain for themselves; otherwise, when they never ever obtain their own API keys, it seems like a magical thing that they can't really do on their own.

So I'm still interested in investigating https://app.freecurrencyapi.com/dashboard, or perhaps we need to think of a different project with a stable, free, easy API. Maybe we make them get their own Pirate Weather key?
